use crate::error::Error;

pub fn fallback() -> Result<(), Error> {
    Ok(())
}
